### PR TITLE
Don't add duplicate custom URLs Closes #2730

### LINKED ISSUE #2730: When custom autocomplete URL added, it can save duplicates
### Steps to reproduce
- long tap the URL bar, and select 'add custom URL' 
- long tap the URL bar again, and re-select 'add custom URL'
- Open Focus, and go to Custom URL list in settings

### Expected behavior
- There is only one custom URL entry 

### Actual behavior
- It lists duplicate URL entries

### Device information
Pixel 2, API 27

### PR DESCRIPTION
**Pull request by ekager**

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteQuickAddPopup.kt [hunk 1]
```diff
@@ -27,13 +27,18 @@ class AutocompleteQuickAddPopup(context: Context, url: String) : PopupWindow() {
         setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))
 
         val button = view.findViewById<Button>(R.id.quick_add_autocomplete_button)
+
+        var URLAlreadyExists = false
```
Comment (sputnikci) [inline app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteQuickAddPopup.kt]: \[detekt\] INFO: \[style/NamingConventionViolation\] All names in the codebase should be matching the naming convention of the codebase\.
