### PR TITLE
GV Turn off TP + Cookie Blocking with Menu Toggle Closes #2894

### LINKED ISSUE #2894: Toggling Tracking Protection in the main menu has no effect with GeckoView
### Steps to reproduce

1. Visit a site that has visible tracking content (see, for example, https://github.com/webcompat/web-bugs/issues/17717)
2. Turn off tracking protection using the toggle in Focus's main menu

### Expected behavior

- The tracking content is visible

### Actual behavior

- The tracking content is blocked

### Device information

I'm *am* seeing this behavior on Focus 6.2 (Build 221931205 :lizard: 62.0.20180709172241).
I'm *am not* seeing this behavior on Klar 4.2 (Build #19), from F-Droid.

### PR DESCRIPTION
**Pull request by ekager**

### CODE REVIEW

File: app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java [hunk 1]
```diff
@@ -185,8 +185,10 @@ public void setBlockingEnabled(boolean enabled) {
                 applyAppSettings();
             } else {
                 if (geckoSession != null) {
```
Comment (pocmo) [inline app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: I wonder why we do the `geckoSession != null` check here. Inside the block we do not use `geckoSession` and if it would be null then `geckoSession.getSettings()` at the beginning of the method would fail already.

File: app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java [hunk 2]
```diff
@@ -185,8 +185,10 @@ public void setBlockingEnabled(boolean enabled) {
...
+                    geckoRuntime.getSettings().setTrackingProtectionCategories(0);
                     geckoRuntime.getSettings().setJavaScriptEnabled(true);
                     geckoRuntime.getSettings().setWebFontsEnabled(true);
+                    geckoRuntime.getSettings().setCookieBehavior(GeckoRuntimeSettings.COOKIE_ACCEPT_ALL);
```
Comment (pocmo) [inline app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: Doesn't this disable all those features globally? Will we re-enable them if a user switches tabs?

Comment (ekager) [reply app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: Yes we reenable if a user switches tabs, setBlockingEnabled is part of tab initialization

File: app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java (hunk 1 above)
Comment (ekager) [reply app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: Yeah that makes sense

**Comment by boek** [comment]
Once this lands lets see if it fixes #2883
