### PR TITLE
WebView should show focus:rights and focus:about URL Closes #2455

### LINKED ISSUE #2455: In Focus Webview Debug, About Focus and Your Rights page have about:blank URL
Going to those pages shows about:blank for Focus webview debug builds, and they are causing the UI tests to fail as well.
screen shot 2018-04-12 at 5 04 50 pm

### PR DESCRIPTION
**Pull request by ekager**

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/browser/LocalizedContent.java [hunk 1]
```diff
@@ -69,7 +69,7 @@ private static void loadAbout(@NonNull final WebView webView) {
 
         final String data = HtmlLoader.loadResourceFile(context, R.raw.about, substitutionMap);
         // We use a file:/// base URL so that we have the right origin to load file:/// css and image resources.
-        webView.loadDataWithBaseURL("file:///android_res/raw/about.html", data, "text/html", "UTF-8", null);
+        webView.loadDataWithBaseURL(URL_ABOUT, data, "text/html", "UTF-8", URL_ABOUT);
```
Comment (pocmo) [inline app/src/main/java/org/mozilla/focus/browser/LocalizedContent.java]: This works as long as those pages do not load or link to any other resources in the raw/ folder.
