### PR TITLE
Catch MalformedURLException in PopupUtils Closes #2390

### LINKED ISSUE #2390: java.net.MalformedURLException
Looks like a new crash from 4.1?

> org.mozilla.focus.popup.PopupUtils.setOrigin
```
java.lang.RuntimeException: 
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
Caused by: java.lang.reflect.InvocationTargetException: 
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
Caused by: java.net.MalformedURLException: 
 
  at java.net.URL.<init> (URL.java:597)
 
  at java.net.URL.<init> (URL.java:487)
 
  at java.net.URL.<init> (URL.java:436)
 
  at org.mozilla.focus.popup.PopupUtils.setOrigin (PopupUtils.kt:71)
 
  at org.mozilla.focus.popup.PopupUtils.createSecurityPopup (PopupUtils.kt:41)
 
  at org.mozilla.focus.fragment.BrowserFragment.showSecurityPopUp (BrowserFragment.java:1098)
 
  at org.mozilla.focus.fragment.BrowserFragment.onClick (BrowserFragment.java:1003)
 
  at android.view.View.performClick (View.java:6303)
 
  at android.view.View$PerformClick.run (View.java:24828)
 
  at android.os.Handler.handleCallback (Handler.java:789)
 
  at android.os.Handler.dispatchMessage (Handler.java:98)
 
  at android.os.Looper.loop (Looper.java:164)
 
  at android.app.ActivityThread.main (ActivityThread.java:6809)
```

### PR DESCRIPTION
**Pull request by ekager**

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/popup/PopupUtils.kt [hunk 1]
```diff
@@ -65,11 +67,18 @@ object PopupUtils {
...
-            val newURL: URL? = URL(url)
-            hostInfo.text = if (newURL != null) newURL.host else url
+            val newURL = try {
+                URL(url)
+            } catch (e: MalformedURLException) {
+                Log.d(LOGTAG, "Could not create URL")
+                hostInfo.text = url
+                return
+            }
+            hostInfo.text = newURL.host
```
Comment (pocmo) [inline app/src/main/java/org/mozilla/focus/popup/PopupUtils.kt]: I think this could be simplified to:

```Kotlin
hostInfo.text = try {
    URL(url).host
} catch (e: MalformedURLException) {
    url
}
```

File: app/src/main/java/org/mozilla/focus/popup/PopupUtils.kt [hunk 2]
```diff
@@ -65,11 +67,18 @@ object PopupUtils {
     }
 
     private fun setOrigin(hostInfo: TextView, origin: String?, url: String) {
+        val LOGTAG = "PopupUtils"
```
Comment (pocmo) [inline app/src/main/java/org/mozilla/focus/popup/PopupUtils.kt]: This should be a constant at the top of the class/object:

```Kotlin
const val LOGTAG = "PopupUtils"
```

Or let's just not log this at all... :)

File: app/src/main/java/org/mozilla/focus/popup/PopupUtils.kt (hunk 1 above)
Comment (ekager) [reply app/src/main/java/org/mozilla/focus/popup/PopupUtils.kt]: Kotlin so fancy!!! Okay :)
