### PR TITLE
Fix flaky web controls UI tests

### LINKED ISSUE #7743: Intermittent UI test failure - < WebControlsTest. verifyDropdownMenuTest >
### Stacktrace: 
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.Spinner, PACKAGE NAME=org.mozilla.focus.debug, RESOURCE_ID=dropDown]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickDropDownForm(BrowserRobot.kt:247)
	at org.mozilla.focus.activity.WebControlsTest$verifyDropdownMenuTest$2.invoke(WebControlsTest.kt:78)
	at org.mozilla.focus.activity.WebControlsTest$verifyDropdownMenuTest$2.invoke(WebControlsTest.kt:76)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifyDropdownMenuTest(WebControlsTest.kt:76)

### LINKED ISSUE #7744: Intermittent UI test failure - < WebControlsTest.verifyTextInputTest>
### Firebase Test Run: 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8104570911125884951/executions/bs.69ab683802a7e112/testcases/2)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8104570911125884951/executions/bs.f6fb6320d04fd58e/testcases/2)
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[PACKAGE NAME=org.mozilla.focus.debug, RESOURCE_ID=textInput]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickAndWriteTextInInputBox(BrowserRobot.kt:300)
	at org.mozilla.focus.activity.WebControlsTest$verifyTextInputTest$2.invoke(WebControlsTest.kt:64)
	at org.mozilla.focus.activity.WebControlsTest$verifyTextInputTest$2.invoke(WebControlsTest.kt:62)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifyTextInputTest(WebControlsTest.kt:62)

### LINKED ISSUE #7747: Intermittent UI test failure - < WebControlsTest.verifyExternalLinksTest>
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=External link]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickLinkMatchingText(BrowserRobot.kt:221)
	at org.mozilla.focus.activity.WebControlsTest$verifyExternalLinksTest$2.invoke(WebControlsTest.kt:93)
	at org.mozilla.focus.activity.WebControlsTest$verifyExternalLinksTest$2.invoke(WebControlsTest.kt:91)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifyExternalLinksTest(WebControlsTest.kt:91)

### PR DESCRIPTION
**Pull request by AndiAJ**
For #7743 fix `verifyDropdownMenuTest` UI test ✅ successfully passed 100x on Firebase.
For #7744 fix `verifyTextInputTest` UI test ✅ successfully passed 100x on Firebase.
For #7747 fix `verifyExternalLinksTest` UI test ✅ successfully passed 100x on Firebase.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [] **QA Needed**

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### GitHub Automation
Fixes #7743
Fixes #7744
Fixes #7747

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt [hunk 1]
```diff
@@ -217,8 +218,24 @@ class BrowserRobot {
     fun clickCopyImageLocation(): ViewInteraction = copyImageLocation.perform(click())
 
     fun clickLinkMatchingText(expectedText: String) {
-        mDevice.findObject(UiSelector().textContains(expectedText)).waitForExists(waitingTime)
-        mDevice.findObject(UiSelector().textContains(expectedText)).also { it.click() }
+        for (i in 1..RETRY_COUNT) {
+            try {
+                mDevice.findObject(UiSelector().textContains(expectedText)).waitForExists(waitingTime)
```
Comment (sv-ohorvath) [inline app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt:223]: you could also use waitingTimeLong if you think it helps

File: app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt [hunk 2]
```diff
@@ -241,18 +258,51 @@ class BrowserRobot {
...
     fun clickDropDownForm() {
-        mDevice.findObject(UiSelector().resourceId("$packageName:id/engineView"))
-            .waitForExists(waitingTime)
-        mDevice.findObject(UiSelector().textContains("Drop-down Form")).waitForExists(waitingTime)
-        dropDownForm.click()
+        for (i in 1..RETRY_COUNT) {
+            try {
+                mDevice.findObject(UiSelector().resourceId("$packageName:id/engineView"))
+                    .waitForExists(waitingTime)
+                mDevice.findObject(UiSelector().textContains("Drop-down Form")).waitForExists(waitingTime)
```
Comment (sv-ohorvath) [inline app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt:265]: could this be replaced with dropDownForm.waitForExists instead? If it's necessary to do so than ignore my comment.

File: app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt [hunk 3]
```diff
@@ -241,18 +258,51 @@ class BrowserRobot {
...
-            .waitForExists(waitingTime)
-        mDevice.findObject(UiSelector().textContains("Calendar Form")).waitForExists(waitingTime)
-        calendarForm.click()
-        mDevice.waitForIdle(waitingTime)
+        for (i in 1..RETRY_COUNT) {
+            try {
+                mDevice.findObject(UiSelector().resourceId("$packageName:id/engineView"))
+                    .waitForExists(waitingTime)
+                mDevice.findObject(UiSelector().textContains("Calendar Form"))
+                    .waitForExists(waitingTime)
```
Comment (sv-ohorvath) [inline app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt:289]: similar comment with the one above

File: automation/taskcluster/androidTest/flank-arm64-v8a.yml [hunk 4]
```diff
@@ -20,8 +20,7 @@ gcloud:
   performance-metrics: true
 
   test-targets:
-    - package org.mozilla.focus.activity
-    - package org.mozilla.focus.privacy
+    - class org.mozilla.focus.activity.WebControlsTest#verifyCalendarFormTest
```
[the remark this answers is not in the document]
Comment (AndiAJ) [reply automation/taskcluster/androidTest/flank-arm64-v8a.yml:23]: forgot about this test yesterday, that's why I'm running it.

File: app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt (hunk 2 above)
Comment (AndiAJ) [reply app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt:265]: I'll give it a try, thanks !

File: app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt (hunk 3 above)
Comment (AndiAJ) [reply app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt:289]: I'll give it a try, thanks !

File: app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt (hunk 1 above)
Comment (AndiAJ) [reply app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt:223]: Yes, thought about it, but I'll leave it with the standard waitingTime, don't think it would make a difference.

File: app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt (hunk 3 above)
Comment (AndiAJ) [reply app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt]: Done !

File: app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt (hunk 2 above)
Comment (AndiAJ) [reply app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt]: Done !

**Comment by AndiAJ** [comment]
Made the changes @sv-ohorvath and successfully re-ran 50x the tests on Firebase.

**Review by AaronMT — APPROVED** [review]

**Comment by AaronMT** [comment]
I'd like to know why these workaround's are needed :/
