### PR TITLE
Closes #2258 Handle external links with GV including market

### LINKED ISSUE #2258: market:// url doesn't work with Geckoview
Entering market://details?id=org.mozilla.firefox&referrer=" +
                "utm_source%3Dmozilla%26utm_medium%3DReferral%26utm_campaign%3Dmozilla-org URL should open a prompt to go to Google Play store, but on geckoview it only shows blank page

### PR DESCRIPTION
**Pull request by ekager**

### CODE REVIEW

File: app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java [hunk 1]
```diff
@@ -274,6 +277,14 @@ public boolean onLoadUri(GeckoSession session, String uri, GeckoSession.Navigati
                         return true;
                     }
 
+                    // Check if we should handle an external link
+                    final Uri urlToURI = Uri.parse(uri);
```
Comment (pocmo) [inline app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: `urlToURI` is a bit hard to read. However I can't come up with a better name. Feel free to just merge if you have no idea either. :)

File: app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java [hunk 2]
```diff
@@ -274,6 +277,14 @@ public boolean onLoadUri(GeckoSession session, String uri, GeckoSession.Navigati
...
+                    if (!UrlUtils.isSupportedProtocol(urlToURI.getScheme()) &&
+                            callback != null &&
+                            IntentUtils.handleExternalUri(getContext(), GeckoWebView.this, uri)) {
+                        return true;
```
Comment (pocmo) [inline app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: `handleExternalUri()` returns a boolean. We may want to return the result here instead of always `true`?
