### PR TITLE
Fixes #4083 - Adds telemetry to the crash reporter

### LINKED ISSUE #4083: Add telemetry for crash reporting

### PR DESCRIPTION
**Pull request by boek**

### CODE REVIEW

**Comment by boek** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) **What questions will you answer with this data?**

* Do users submit crash reports?

2) **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**

* We want to verify that the crash reports in the Google Play Store and Socorro match up

3) **What alternative methods did you consider to answer these questions? Why were they not sufficient?**

Currently we can only assume that a large percentage of users don't submit a crash report

4) **Can current instrumentation answer these questions?**

* No

5) **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**

* Category 2.

**Events**

| Event                                    | category | method     | object | extra  |
|------------------------------------------|----------|------------|--------|--------|
| Open Crash Reporter | action   | show | crash_reporter |    |
| Close Tab | action   | action | click | crash_reporter |  submit_crash*  |

* - Crash report was submitted

6) **How long will this data be collected?**

* @mmccorks will permanently monitor this data.

7) **What populations will you measure?**

* All release, beta, and nightly users with telemetry enabled.

8) **Please provide a general description of how you will analyze this data.**

* Re-dash queries + dashboards

9) **Where do you intend to share the results of your analysis?**

* Only on re-dash and with mobile teams.

**Comment by boek** [comment]
@liuche ready for data review :)

File: app/src/main/java/org/mozilla/focus/fragment/CrashReporterFragment.kt [hunk 1]
```diff
@@ -24,8 +25,12 @@ class CrashReporterFragment : Fragment() {
     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
         super.onViewCreated(view, savedInstanceState)
 
+        TelemetryWrapper.crashReporterOpened()
+
         closeTabButton.setOnClickListener {
```
Comment (liuche) [inline app/src/main/java/org/mozilla/focus/fragment/CrashReporterFragment.kt]: Is there another way to close this button? by hitting back maybe? Just want to make sure you're not losing any events, and only collecting explicit clicks.

File: docs/Telemetry.md [hunk 2]
```diff
@@ -308,6 +308,14 @@ The event ping contains a list of events ([see event format on readthedocs.io](h
 | Autocomplete URL tip tapped | action   | click | tip | add_autocomplete_url_tip    |        |
 | Homescreen tips enabled/disabled | action   | click | tip | add_to_homescreen_tip    |        |
 
+### Homescreen Tips
+| Event               | category | method | object         | extra         |
+|---------------------|----------|--------|----------------|---------------|
+| Open Crash Reporter | action   | show   | crash_reporter |               |
+| Close Tab           | action   | click  | crash_reporter | submit_crash  |
```
Comment (liuche) [inline docs/Telemetry.md]: Alternatively you could just write true/false instead of submit_crash - the name of the value doesn't matter, just all the possible values themselves.

**Comment by liuche** [comment]
data-review+
