### PR TITLE
Set default value for Renderer preference in settings fragment based …

### LINKED ISSUE #2975: Focus:test renderer switch is always off by default upon startup, regardless of the renderer
## Steps to reproduce
Build FocusArmNightly, load it on device, and go to focus:test

### Expected behavior
Since Nightly has Geckoview by default, the new renderer switch should be set to true

### Actual behavior
New renderer switch is set to false 
According to @colintheshots , Until a shared preference is set, the value defaults true. The settings page reflects the shared preference, not the default.

### Device information

* Android device: Moto G5
* Focus version: master branch

### PR DESCRIPTION
**Pull request by colintheshots**
…upon config, Closes #2975

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/settings/ExperimentsSettingsFragment.kt [hunk 1]
```diff
@@ -6,20 +6,26 @@ package org.mozilla.focus.settings
...
     companion object {
         const val FRAGMENT_TAG = "ExperimentSettings"
     }
 
-    var rendererPreferenceChanged = false
+    private var rendererPreferenceChanged = false
 
     override fun onCreatePreferences(savedInstanceState: Bundle?, rootKey: String?) {
         addPreferencesFromResource(R.xml.experiments_settings)
+        val enginePref : SwitchPreference? = preferenceManager.findPreference(RENDERER_PREFERENCE_KEY) as SwitchPreference?
```
Comment (sputnikci) [inline app/src/main/java/org/mozilla/focus/settings/ExperimentsSettingsFragment.kt]: \[detekt\] INFO: \[style/MaxLineLength\] Line detected that is longer than the defined maximum line length in the code style\.

File: app/src/main/java/org/mozilla/focus/settings/ExperimentsSettingsFragment.kt [hunk 2]
```diff
@@ -6,20 +6,26 @@ package org.mozilla.focus.settings
...
+        enginePref?.isChecked = preferenceManager.sharedPreferences.getBoolean(RENDERER_PREFERENCE_KEY, Config.DEFAULT_NEW_RENDERER)
```
Comment (sputnikci) [inline app/src/main/java/org/mozilla/focus/settings/ExperimentsSettingsFragment.kt]: \[detekt\] INFO: \[style/MaxLineLength\] Line detected that is longer than the defined maximum line length in the code style\.
