### PR TITLE
Open all in-content links with sessions Closes #2107

### LINKED ISSUE #2107: "What's New" link inside the menu doesn't open in a modal view
Steps to reproduce:

- Tap `menu` -> `Help`. Notice that the link opens in an in-content modal view. This enables you to go back by tapping the arrow on the top-left corner.
  - Try it with other links, e.g. `menu` -> `Settings` -> `Privacy Notice`
- Tap `menu` -> `What’s new`. Notice that the link opens in a Focus app tab.

The behaviour of “What’s New” should follow the behaviour of other in-content links.

### PR DESCRIPTION
**Pull request by ekager**

### CODE REVIEW

**Comment by ekager** [comment]
Worked with @brampitoyo to add initial erase FAB animation and new tab icons in the Settings Menu to improve interaction

File: app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt [hunk 1]
```diff
@@ -81,12 +81,10 @@ class ManualAddSearchEngineSettingsFragment : BaseSettingsFragment() {
...
         val openLearnMore = {
-            val url = SupportUtils.getSumoURLForTopic(activity, SupportUtils.SumoTopic.ADD_SEARCH_ENGINE)
-            val title = (activity as AppCompatActivity).supportActionBar?.title.toString()
-            val intent = InfoActivity.getIntentFor(activity, url, title)
-            activity.startActivity(intent)
-
             TelemetryWrapper.addSearchEngineLearnMoreEvent()
+            SessionManager.getInstance().createSession(Source.MENU, SupportUtils
+                .getSumoURLForTopic(activity, SupportUtils.SumoTopic.ADD_SEARCH_ENGINE))
+            activity.finish()
```
Comment (pocmo) [inline app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt]: flow nit: I'd always perform the action first and then send a telemetry probe.

File: app/src/main/java/org/mozilla/focus/utils/SupportUtils.java [hunk 2]
```diff
@@ -19,6 +20,11 @@
     public static final String HELP_URL = "https://support.mozilla.org/kb/what-firefox-focus-android";
     public static final String DEFAULT_BROWSER_URL = "https://support.mozilla.org/kb/set-firefox-focus-default-browser-android";
 
+    public static final String PRIVACY_NOTICE_URL = "https://www.mozilla" +
+            ".org/privacy/firefox-focus/";
+    public static final String PRIVACY_NOTICE_KLAR_URL = "https://www.mozilla" +
+            ".org/de/privacy/firefox-klar/";
+
```
Comment (pocmo) [inline app/src/main/java/org/mozilla/focus/utils/SupportUtils.java]: This concatenation is weird. Is this intentional?

File: app/src/main/res/drawable/ic_tab_new.xml [hunk 3]
```diff
@@ -0,0 +1,6 @@
+<vector android:height="24dp" android:viewportHeight="16"
```
Comment (pocmo) [inline app/src/main/res/drawable/ic_tab_new.xml]: nit: license

File: app/src/main/java/org/mozilla/focus/widget/FloatingEraseButton.java [hunk 4]
```diff
@@ -9,6 +9,9 @@
 import android.support.design.widget.FloatingActionButton;
 import android.util.AttributeSet;
 import android.view.View;
+import android.view.animation.AnimationUtils;
+
+import org.mozilla.focus.R;
 
 public class FloatingEraseButton extends FloatingActionButton {
```
Comment (pocmo) [inline app/src/main/java/org/mozilla/focus/widget/FloatingEraseButton.java]: Please test this behavior with:

* custom tabs (no fab)
* scrolling (should still disappear/reappear)
* multiple tabs
* switching between foreground/background (with "keep activities" enabled/disabled)

Comment (ekager) [reply app/src/main/java/org/mozilla/focus/widget/FloatingEraseButton.java]: I believe it works in all these cases, did you find something that says otherwise?

Comment (pocmo) [reply app/src/main/java/org/mozilla/focus/widget/FloatingEraseButton.java]: Nope. But I also didn't test all variations myself. :)
