### PR TITLE
Fixes SearchEngineSelectionTest - Closes #2763 🌮

### LINKED ISSUE #2763: SearchEngineSelectionTest.java is failing
### Steps to reproduce
run automated test

### Expected behavior
test should select "Search" option on Settings menu

### Actual behavior
test selects "Privacy & Security" option on Settings menu

### Device information
* emulator: Nexus 5X API 23

image

### PR DESCRIPTION
**Pull request by rpappalax**
r? @npark-mozilla

### CODE REVIEW

File: app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java [hunk 1]
```diff
@@ -21,19 +21,33 @@
...
 
+import java.util.Arrays;
+
 import static junit.framework.Assert.assertEquals;
 import static junit.framework.Assert.assertTrue;
 import static org.mozilla.focus.fragment.FirstrunFragment.FIRSTRUN_PREF;
 import static org.mozilla.focus.helpers.EspressoHelper.openSettings;
 import static org.mozilla.focus.helpers.TestHelper.waitingTime;
 import static org.mozilla.focus.helpers.TestHelper.webPageLoadwaitingTime;
+import static org.mozilla.focus.helpers.TestHelper.webView;
```
Comment (sputnikci) [inline app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java]: \[Checkstyle\] ERROR: Unused import \- org\.mozilla\.focus\.helpers\.TestHelper\.webView\.

File: app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java [hunk 2]
```diff
@@ -60,85 +74,140 @@ public void tearDown() throws Exception {
...
-        TestHelper.inlineAutocompleteEditText.clearTextField();
-        TestHelper.inlineAutocompleteEditText.setText("mozilla focus");
-        TestHelper.hint.waitForExists(waitingTime);
-
-        // Check the search hint bar is correctly displayed
-        assertTrue(TestHelper.hint.getText().equals("Search for mozilla focus"));
-        TestHelper.hint.click();
+
+        // Open [settings menu] and select Search
+        {
```
Comment (npark-mozilla) [inline app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java]: we probably won't need open/close braces for each section, have them separated by an empty line should be enough, with the comment on top

File: app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java [hunk 3]
```diff
@@ -60,85 +74,140 @@ public void tearDown() throws Exception {
...
+            assertTrue(TestHelper.inlineAutocompleteEditText.waitForExists(waitingTime));
+            openSettings();
+            searchEngineSelectorLabel.click();
+        }
```
Comment (npark-mozilla) [inline app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java]: for ease of debug, it always helps to check whether the UI action caused intended result.  so in this case, you could check whether the screen really got updated after .click().  this applies to all the other ui actions below

File: app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java [hunk 4]
```diff
@@ -60,85 +74,140 @@ public void tearDown() throws Exception {
...
+            UiObject defaultSearchEngine = TestHelper.mDevice.findObject(new UiSelector()
+                    .text(mSearchEngine)
+                    .resourceId("android:id/title"));
+
+            assertTrue(defaultSearchEngine.getText().equals(mSearchEngine));
+            TestHelper.pressBackKey();
+            TestHelper.pressBackKey();
+        }
+
+
```
Comment (npark-mozilla) [inline app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java]: let's only use single empty line between a chunk of actions, instead of 2

File: app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java (hunk 2 above)
Comment (rpappalax) [reply app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java]: thanks @npark-mozilla, i saw several test cases with this formatting.  wasn't sure if we were adhereing to a given standard

File: app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java [hunk 5]
```diff
@@ -60,85 +74,140 @@ public void tearDown() throws Exception {
...
+            googleWebView.waitForExists(waitingTime);
+            TestHelper.progressBar.waitForExists(webPageLoadwaitingTime);
+            Assert.assertTrue(TestHelper.progressBar.waitUntilGone(webPageLoadwaitingTime));
+            assertTrue(TestHelper.browserURLbar.getText().contains(mSearchEngine.toLowerCase()));
+            assertTrue(TestHelper.browserURLbar.getText().contains("mozilla"));
+            assertTrue(TestHelper.browserURLbar.getText().contains("focus"));
+        }
+
+
+        // Do another search on text string
```
Comment (rpappalax) [inline app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java]: @npark-mozilla was the original intent of this to simply repeat the above block to verify consistency?  if so, I'll just duplicate it

File: app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java (hunk 4 above)
Comment (rpappalax) [reply app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java]: k

File: app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java (hunk 3 above)
Comment (rpappalax) [reply app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java]: so, do a waitForExists() and then an assert to verify?

**Comment by npark-mozilla** [comment]
@pocmo curious, the taskcluster job is reported as failed above, but when I retriggered the job it passed.  @boek could you force merge this pr please, since all jobs seems to be passing? thanks!

**Comment by pocmo** [comment]
Just retriggered the run by renaming the PR..
