### PR TITLE
Move startup perf measurements to a background thread

### LINKED ISSUE #7216: -69ms regression to COLD MAIN first frame
_see also ~60ms regression to both view and main in fenix https://github.com/mozilla-mobile/fenix/issues/25607_

We see a regression of ~69ms from the 6/9 Nightly (605ms) to the 6/10 Nightly (674ms):

image

### PR DESCRIPTION
**Pull request by badboy**
Similar fix as done on Fenix: https://github.com/mozilla-mobile/fenix/pull/26165
Should avoid loading the Glean core library too early, but still records
the data just fine.

Note that Focus doesn't record startup time, so nothing to delay there.

Fixes #7216

---

I haven't run that locally yet, so I'm not 100% sure if it addresses it all.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### GitHub Automation
Fixes #7216

### CODE REVIEW

**Comment by badboy** [comment]
Ok, the test fails so I need to look into this.

**Comment by badboy** [comment]
It doesn't fail for me locally.

**Comment by mcarare** [comment]
See https://github.com/mozilla-mobile/fenix/pull/26544 for the Fenix fix for the tests.

File: app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupTypeTelemetry.kt [hunk 1]
```diff
@@ -69,8 +73,11 @@ class StartupTypeTelemetry(
         val startupPath = startupPathProvider.startupPathForActivity
         val label = getTelemetryLabel(startupState, startupPath)
 
-        PerfStartup.startupType[label].add(1)
-        logger.info("Recorded start up: $label")
+        @OptIn(DelicateCoroutinesApi::class)
+        GlobalScope.launch(Dispatchers.IO) {
+            PerfStartup.startupType[label].add(1)
+            logger.info("Recorded start up: $label")
+        }
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupTypeTelemetry.kt:80]: This may cause tests to fail since it moves execution to another thread while tests run on Main.
Similar to https://github.com/mozilla-mobile/fenix/pull/26544/files we'd need a way to have the threading controllable from tests. 
@badboy We can help with this to get the tests to pass in CI and then land this patch.

**Comment by badboy** [comment]
Rebased and applied the same fix that Fenix did
