### PR TITLE
Fix search engine writer url format

### LINKED ISSUE #2487: Custom search plugins written to disk still assume that search terms are at the end of the URL
We recently changed our search URL validation to not enforce that the '%s' placeholder is at the end of the string. However I just noticed that when writing the URL to disk we remove the last two characters and replace it with {searchTerms}.

### PR DESCRIPTION
**Pull request by RomanWuattier**
* The URL validation doesn't enforce `%s` placeholder anymore. The
writer now replaces `%s` by `{searchTers}` everywhere in the template.
* Unit test `SearchEngineWriter`

Closes #2487

### CODE REVIEW

**Comment by boek** [comment]
Hey @RomanWuattier, thanks for the contribution! I'll take a peek later today

File: app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+            "<Description>testEngine</Description>" +
+            "<Url template=\"testEngine/?q={searchTerms}/tests\" type=\"text/html\"/>" +
+            "</OpenSearchDescription>"
+
+        assertEquals(middleSearchTermXml,
+            SearchEngineWriter.buildSearchEngineXML("testEngine", "testEngine/?q=%s/tests", createBitmap()))
+    }
+
+    private fun createBitmap() = Bitmap.createBitmap(10, 10, Bitmap.Config.ARGB_8888)
+}
```
Comment (sputnikci) [inline app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt]: \[detekt\] INFO: \[style/NewLineAtEndOfFile\] Checks whether files end with a line separator\.

File: app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+
+@RunWith(RobolectricTestRunner::class)
+class SearchEngineWriterTest {
+
+    @Test
+    fun buildSearchEngineXML() {
+        val endSearchTermXml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>" +
+            "<OpenSearchDescription xmlns=\"http://a9.com/-/spec/opensearch/1.1/\">" +
+            "<ShortName>testEngine</ShortName>" +
+            "<Image height=\"16\" width=\"16\">data:image/png;base64,Qml0bWFwICgxMCB4IDEwKSBjb21wcmVzc2VkIGFzIFBORyB3aXRoIHF1YWxpdHkgMTAw\n</Image>" +
```
Comment (sputnikci) [inline app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt]: \[detekt\] INFO: \[style/MaxLineLength\] Line detected that is longer than the defined maximum line length in the code style\.

File: app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+            "<Url template=\"testEngine/?q={searchTerms}\" type=\"text/html\"/>" +
+            "</OpenSearchDescription>"
+
+        assertEquals(endSearchTermXml,
+            SearchEngineWriter.buildSearchEngineXML("testEngine", "testEngine/?q=%s", createBitmap()))
+
+        val middleSearchTermXml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>" +
+            "<OpenSearchDescription xmlns=\"http://a9.com/-/spec/opensearch/1.1/\">" +
+            "<ShortName>testEngine</ShortName>" +
+            "<Image height=\"16\" width=\"16\">data:image/png;base64,Qml0bWFwICgxMCB4IDEwKSBjb21wcmVzc2VkIGFzIFBORyB3aXRoIHF1YWxpdHkgMTAw\n</Image>" +
```
Comment (sputnikci) [inline app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt]: \[detekt\] INFO: \[style/MaxLineLength\] Line detected that is longer than the defined maximum line length in the code style\.

File: app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+            "<Description>testEngine</Description>" +
+            "<Url template=\"testEngine/?q={searchTerms}/tests\" type=\"text/html\"/>" +
+            "</OpenSearchDescription>"
+
+        assertEquals(middleSearchTermXml,
+            SearchEngineWriter.buildSearchEngineXML("testEngine", "testEngine/?q=%s/tests", createBitmap()))
+    }
+
+    private fun createBitmap() = Bitmap.createBitmap(10, 10, Bitmap.Config.ARGB_8888)
```
Comment (sputnikci) [inline app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt]: \[detekt\] INFO: \[style/MagicNumber\] Report magic numbers\. Magic number is a numeric literal that is not defined as a constant and hence it's unclear what the purpose of this number is\. It's better to declare such numbers as constants and give them a proper name\. By default, \-1, 0, 1, and 2 are not considered to be magic numbers\.

Comment (sputnikci) [inline app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt]: \[detekt\] INFO: \[style/MagicNumber\] Report magic numbers\. Magic number is a numeric literal that is not defined as a constant and hence it's unclear what the purpose of this number is\. It's better to declare such numbers as constants and give them a proper name\. By default, \-1, 0, 1, and 2 are not considered to be magic numbers\.

File: app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+            "<Description>testEngine</Description>" +
+            "<Url template=\"testEngine/?q={searchTerms}/tests\" type=\"text/html\"/>" +
+            "</OpenSearchDescription>"
+
+        assertEquals(middleSearchTermXml,
+            SearchEngineWriter.buildSearchEngineXML("testEngine", "testEngine/?q=%s/tests", createBitmap()))
+    }
+
+    private fun createBitmap(): Bitmap {
+        val width = 10
```
Comment (sputnikci) [inline app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt]: \[detekt\] INFO: \[style/MagicNumber\] Report magic numbers\. Magic number is a numeric literal that is not defined as a constant and hence it's unclear what the purpose of this number is\. It's better to declare such numbers as constants and give them a proper name\. By default, \-1, 0, 1, and 2 are not considered to be magic numbers\.

File: app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+        val height = 10
```
Comment (sputnikci) [inline app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt]: \[detekt\] INFO: \[style/MagicNumber\] Report magic numbers\. Magic number is a numeric literal that is not defined as a constant and hence it's unclear what the purpose of this number is\. It's better to declare such numbers as constants and give them a proper name\. By default, \-1, 0, 1, and 2 are not considered to be magic numbers\.

File: app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+package org.mozilla.focus.search
+
+import android.graphics.Bitmap
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.robolectric.RobolectricTestRunner
+import org.junit.Assert.assertEquals
+
+@RunWith(RobolectricTestRunner::class)
+class SearchEngineWriterTest {
```
Comment (pocmo) [inline app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt]: 💯 Thanks for adding a test!

**Comment by RomanWuattier** [comment]
@pocmo Commits are squashed :)
