### PR TITLE
Closes #1668 - Use Fragment newInstance and add null checks.

### LINKED ISSUE #1668: Null check in SettingsFragment
Broken SwitchLocaleTest because getArguments is null.

### PR DESCRIPTION
**Pull request by liuche**
Fallout from #1617.

### CODE REVIEW

**Comment by liuche** [comment]
Green BB UITests: https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/build/5a0228c991f506000193118b#uitests

File: app/src/main/java/org/mozilla/focus/settings/SettingsFragment.java [hunk 1]
```diff
@@ -185,7 +191,7 @@ public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, Strin
 
             // The easiest way to ensure we update the language is by replacing the entire fragment:
             getFragmentManager().beginTransaction()
-                    .replace(R.id.container, new SettingsFragment())
+                    .replace(R.id.container, SettingsFragment.newInstance(null, R.xml.settings, R.string.menu_settings))
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/settings/SettingsFragment.java]: nit:  We use duplicate these resource arguments twice (putting them in danger of getting out of sync), here and in `SettingsActivity.onCreate`, when all we're really trying to say is, "Show top level settings".

It may be outside the scope of this quick fix, but I feel like `newInstance` should instead take a single argument with the screen we want, e.g. `enum SettingsScreen { TOP_LEVEL, ... }`.

Comment (liuche) [reply app/src/main/java/org/mozilla/focus/settings/SettingsFragment.java]: I like that idea! But yeah, I don't want to do it in this fix so I filed #1671 for it.
