### PR TITLE
Hide data: Urls and show focus:<keyword> Closes #2506

### LINKED ISSUE #2506: Klar Geckoview does not display focus:<keyword> in About Firefox /Help/ Your Rights / Privacy Notic
Please let me know if this is not a bug, or geckoview limitation.  UI Test is failing on Klar on this, and I'll need to disable the test if that is the case.

### Steps to reproduce
Go to above mentioned pages from settings.
### Expected behavior
Show 'about: <keyword> on the url side
### Actual behavior
shows raw doc info as below:
screen shot 2018-04-23 at 11 59 04 pm

### Device information

* On Nexus 5X API 27 Sim

### PR DESCRIPTION
**Pull request by ekager**
The reason I had to do it this way (saving the internal data:text.html;base64... link) is even if I overrode the link on the current page, it would not save in the session history, so going back, forward, or even reloading the page would show the data:text... link again. Let me know if you think there is a better way!

### CODE REVIEW

File: app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java [hunk 1]
```diff
@@ -397,7 +419,7 @@ public void onNewSession(GeckoSession session, String uri, GeckoResponse<GeckoSe
         }
 
         private GeckoSession.TrackingProtectionDelegate createTrackingProtectionDelegate() {
-           return new GeckoSession.TrackingProtectionDelegate() {
+            return new GeckoSession.TrackingProtectionDelegate() {
```
Comment (boek) [inline app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: nit: extra space

File: app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java [hunk 2]
```diff
@@ -444,6 +466,10 @@ public void exitFullscreen() {
         @Override
         public void loadData(String baseURL, String data, String mimeType, String encoding, String historyURL) {
             geckoSession.loadData(data.getBytes(Charsets.UTF_8), mimeType, baseURL);
+            currentUrl = baseURL;
+            if (currentUrl.equals(LocalizedContent.URL_RIGHTS) || currentUrl.equals(LocalizedContent.URL_ABOUT)) {
+                isLoadingInternalUrl = true;
```
Comment (boek) [inline app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: Could this be collapsed to:?
```
isLoadingInternalUrl = currentUrl.equals(LocalizedContent.URL_RIGHTS) || currentUrl.equals(LocalizedContent.URL_ABOUT)
```

File: app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java (hunk 1 above)
Comment (ekager) [reply app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: It was actually one space to the left somehow... I dunno
