### PR TITLE
For #7678 - Redone all the navigation from lockscreen,search widget and custom tab

### LINKED ISSUE #7678: Search widget unlocks fingerprint lock
## Steps to reproduce
Enable fingerprint to unlock app
On the android home screen, add the widget to Search the web
Use it and enter a link

### Expected behavior
You are stopped from accessing previous open links with the fingerprint

### Actual behavior
You can access the links

### Device information

* Android device: Samsung S8 (Android 9), Samsung S10 (Android 12)
* Focus version: 105.0.7

### PR DESCRIPTION
**Pull request by iorgamgabriel**
If the lockScreen is active doesn't matter from where the user enters in the app the lockScreen should appear. 

If a browsing page is open and the users closes the app but doesn't removed it from background , when he opens again the app he should be redirected to that page (if the lockScreen is active it should appear first and after that the browsing page ).

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### GitHub Automation
Fixes #7678

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetNavigation.kt [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+import org.mozilla.focus.state.AppAction
+import org.mozilla.focus.utils.SearchUtils
+
+object SearchWidgetNavigation {
+
+    /**
+     * Method used to handle all the navigation from Search widget ,app icon ,lockscreen and
+     * custom tab.
+     */
+    fun handleAppNavigation(
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetNavigation.kt:26]: Can the parameters be documented?

File: app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetNavigation.kt [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+        bundle: Bundle?,
+        activity: Activity,
+        navigator: () -> Unit,
+        splashScreenPreDrawListener: () -> Unit,
+        unlock: () -> Unit,
+    ) {
+        val voiceSearchText = bundle?.getString(BaseVoiceSearchActivity.SPEECH_PROCESSING)
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetNavigation.kt:33]: nit: It seems like we have four cases. Can they be better grouped by using spaces maybe together with a small comment about what scenario each case evaluates? This would hopefully help with helping other down the line and prevent regressions. 
Giving the importance of it unit tests are more than welcomed.

File: app/src/main/java/org/mozilla/focus/state/AppState.kt [hunk 3]
```diff
@@ -80,7 +81,7 @@ sealed class Screen {
     /**
      * The application is locked (and requires unlocking).
      */
-    object Locked : Screen()
+    data class Locked(val bundle: Bundle? = null) : Screen()
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/focus/state/AppState.kt:84]: Can documentation be added for the new parameter?

File: app/src/main/java/org/mozilla/focus/state/AppAction.kt [hunk 4]
```diff
@@ -51,7 +52,7 @@ sealed class AppAction : Action {
     /**
      * The app should get locked.
      */
-    object Lock : AppAction()
+    data class Lock(val bundle: Bundle? = null) : AppAction()
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/focus/state/AppAction.kt:55]: Can documentation be added for the new parameter?

File: app/src/main/java/org/mozilla/focus/activity/MainActivity.kt [hunk 5]
```diff
@@ -302,6 +253,26 @@ open class MainActivity : LocaleAwareAppCompatActivity() {
...
+            intent.extras,
+            this,
+            splashScreenPreDrawListener = {
+                setSplashScreenPreDrawListener(intent)
+            },
+            navigator = {
+                lifecycle.addObserver(navigator)
+            },
+            unlock = {
+            },
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/focus/activity/MainActivity.kt:272]: Can defaults be provided in `handleAppNavigation` for the parameters which are not mandatory?

**Review by Mugurell — COMMENTED** [review]
First pass. 
I understand the solution here is to pass the intent extras through `BiometricAuthenticationFragment` which would resume the expected app opening flow after the user authenticates.
The code does get a little brittle (could use some tests) and it starts to show that Focus needs a proper navigation refactoring but given the importance of the fix it seems like we'll have to patch things up and come back to this later 😶.

File: app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationFragment.kt [hunk 6]
```diff
@@ -100,5 +109,10 @@ class BiometricAuthenticationFragment : BaseFragment(), AuthenticationDelegate {
 
     companion object {
         const val FRAGMENT_TAG = "biometric-authentication-fragment"
+        fun addBiometricAuthenticationBundle(bundle: Bundle? = null): BiometricAuthenticationFragment {
```
[the remark this answers is not in the document]
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationFragment.kt:112]: Done

File: app/src/main/java/org/mozilla/focus/activity/MainActivity.kt [hunk 7]
```diff
@@ -118,15 +113,18 @@ open class MainActivity : LocaleAwareAppCompatActivity() {
 
         val safeIntent = SafeIntent(intent)
 
-        handleSearchWidgetNavigation(safeIntent)
+        if (savedInstanceState == null) {
+            handleAppNavigation(safeIntent)
+        } else {
+            lifecycle.addObserver(navigator)
+        }
```
[the remark this answers is not in the document]
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/activity/MainActivity.kt:120]: If I don't put the else line when the user changes the theme or something else that recreates the activity , the app will not have a back stack .

File: app/src/main/java/org/mozilla/focus/activity/MainActivity.kt [hunk 8]
```diff
@@ -139,35 +137,19 @@ open class MainActivity : LocaleAwareAppCompatActivity() {
...
             object : ViewTreeObserver.OnPreDrawListener {
                 override fun onPreDraw(): Boolean {
                     return if (System.currentTimeMillis() >= endTime) {
-                        showFirstScreen(safeIntent)
+                        SearchWidgetNavigation.showFirstScreen(
+                            safeIntent.extras,
+                            this@MainActivity,
+                            navigator = {
+                                lifecycle.addObserver(navigator)
+                            },
```
[the remark this answers is not in the document]
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/activity/MainActivity.kt:151]: Done

File: app/src/main/java/org/mozilla/focus/activity/MainActivity.kt [hunk 9]
```diff
@@ -302,6 +253,26 @@ open class MainActivity : LocaleAwareAppCompatActivity() {
...
+    private fun handleAppNavigation(intent: SafeIntent) {
+        if (components.appStore.state.screen == Screen.Locked()) {
+            components.appStore.dispatch(AppAction.Lock(intent.extras))
+            lifecycle.addObserver(navigator)
+            return
+        }
+        SearchWidgetNavigation.handleAppNavigation(
+            intent.extras,
+            this,
+            splashScreenPreDrawListener = {
```
[the remark this answers is not in the document]
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/activity/MainActivity.kt:265]: Done

File: app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetNavigation.kt [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+import mozilla.telemetry.glean.private.NoExtras
+import org.mozilla.focus.GleanMetrics.SearchWidget
+import org.mozilla.focus.activity.IntentReceiverActivity
+import org.mozilla.focus.ext.components
+import org.mozilla.focus.ext.settings
+import org.mozilla.focus.perf.Performance
+import org.mozilla.focus.state.AppAction
+import org.mozilla.focus.utils.SearchUtils
+
+object SearchWidgetNavigation {
```
[the remark this answers is not in the document]
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetNavigation.kt:20]: Done

File: app/src/main/java/org/mozilla/focus/activity/MainActivity.kt (hunk 5 above)
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/activity/MainActivity.kt:272]: Done

File: app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt [hunk 11]
```diff
@@ -207,7 +208,7 @@ class MainActivityNavigation(
     /**
      * Lock app.
      */
-    fun lock() {
+    fun lock(bundle: Bundle? = null) {
```
[the remark this answers is not in the document]
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt:211]: Done

File: app/src/main/java/org/mozilla/focus/state/AppAction.kt (hunk 4 above)
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/state/AppAction.kt:55]: Done

File: app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetNavigation.kt (hunk 1 above)
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetNavigation.kt]: Done

File: app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetNavigation.kt (hunk 2 above)
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetNavigation.kt]: Done

File: app/src/main/java/org/mozilla/focus/state/AppState.kt (hunk 3 above)
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/state/AppState.kt:87]: Done

File: app/src/main/java/org/mozilla/focus/state/AppAction.kt (hunk 4 above)
Comment (iorgamgabriel) [reply app/src/main/java/org/mozilla/focus/state/AppAction.kt:55]: Done

File: app/src/test/java/org/mozilla/focus/searchwidget/ExternalIntentNavigationTest.kt [hunk 12]
```diff
@@ -0,0 +1,183 @@
...
+        assertFalse(result)
+        browserStore.waitUntilIdle()
+        assertEquals(0, browserStore.state.allTabs.size)
+        appStore.waitUntilIdle()
+        assertEquals(Screen.Home, appStore.state.screen)
+    }
+}
+
+/**
+ * Shadow of [Performance] tha will have [processIntentIfPerformanceTest] always return `true`.
```
Comment (Mugurell) [inline app/src/test/java/org/mozilla/focus/searchwidget/ExternalIntentNavigationTest.kt:176]:
```suggestion
 * Shadow of [Performance] that will have [processIntentIfPerformanceTest] always return `true`.
```

**Review by Mugurell — APPROVED** [review]
Thank you! LGTM.
