### PR TITLE
Only handle images in Context Menu Closes #2206

### LINKED ISSUE #2206: Incorrect options in the Video context menus
Build: Klar+GeckoView 4.0

STR:
1. Go to a youtube video, or http://techslides.com/demos/sample-videos/small.ogv.
2. Long tap the video playing.

Expected results:
Video context menu should be displayed: share video, play, pause, save video, etc. - as on Nightly
Or no context menu at all - as on Focus.

Actual result:
The image context menu appears, with the options: share image, copy image address.

### PR DESCRIPTION
**Pull request by ekager**

### CODE REVIEW

File: app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java [hunk 1]
```diff
@@ -195,7 +195,11 @@ public void onContextMenu(GeckoSession session, int screenX, int screenY, String
                     if (elementSrc != null && uri != null) {
                         callback.onLongPress(new HitTarget(true, uri, true, elementSrc));
                     } else if (elementSrc != null) {
-                        callback.onLongPress(new HitTarget(false, null, true, elementSrc));
+                        if (elementSrc.endsWith("jpg") || elementSrc.endsWith("gif") ||
+                                elementSrc.endsWith("tif") || elementSrc.endsWith("bmp") ||
+                                elementSrc.endsWith("png")) {
+                            callback.onLongPress(new HitTarget(false, null, true, elementSrc));
+                        }
```
Comment (pocmo) [inline app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: I asked snorp whether GeckoView can tell us what the element is. They will add an API for us - I filed a bug for that: https://bugzilla.mozilla.org/show_bug.cgi?id=1445240

I'll merge this here as a workaround and file a new issue to clean that up once the new API is available.

Comment (pocmo) [reply app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java]: Filed #2283
