### PR TITLE
For #7423: Replace icon for navigate up/back button.

### LINKED ISSUE #7423: [RTL L10N] The "Languages" page's back arrow is incorrect
## Steps to reproduce
1. Set your device to a RTL language, like Persian (fa).
2. Open Focus - Settings - General - Languages, and observe the back arrow.

### Expected behavior
The back arrow is pointing to the right, like all the other back arrows inside the app.

### Actual behavior
The back arrow is pointing to the left.

### Device information
* Android device: all
* Focus version: Focus Nightly 105.0a1, Beta 104.0b1
* Please see the short video below:

https://user-images.githubusercontent.com/40694158/181462351-aec194b4-38ea-402b-a0bc-c0f185895693.mp4

Screenshot_3

### PR DESCRIPTION
**Pull request by mcarare**
The new icon is already used in all other app fragments.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### GitHub Automation
Fixes #7423

### CODE REVIEW

**Review by iorgamgabriel — APPROVED** [review]

File: app/src/main/java/org/mozilla/focus/compose/Modifier.kt [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+import androidx.compose.ui.composed
+import androidx.compose.ui.draw.scale
+import androidx.compose.ui.platform.LocalLayoutDirection
+import androidx.compose.ui.unit.LayoutDirection
+
+/**
+ * Modifier used for performing auto mirroring in RTL for composable.
+ */
+@Stable
+fun Modifier.autoMirroringModifier(): Modifier = composed {
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/focus/compose/Modifier.kt:18]: I think most of the current modifiers are named to express an action that will be executed or property that is updated for the Composable without the `Modifier` suffix.
Can this be just `autoMirror`?
