### PR TITLE
Decode URI special characters before creating File - closes #1011

### LINKED ISSUE #1011: Opening downloaded APK from snackbar shows error: "There was a problem parsing the package."
When downloading an APK (usually an update I get from buddybuild) and trying to install the APK from the Snackbar ("open" action) an error dialog pops up saying: "There was a problem parsing the package.". When opening the APK from the download manager notification everything is fine though.

### PR DESCRIPTION
**Pull request by ekager**
In reference to (#1011), this includes a check to see if the file exists before showing the snackbar and I added Uri decoding to take care of special properties that should only appear in the Uri and not when creating the File or displaying the file name.

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/broadcastreceiver/DownloadBroadcastReceiver.java [hunk 1]
```diff
@@ -63,13 +63,14 @@ private void displaySnackbar(final Context context, long completedDownloadRefere
...
-
-                    final File file = new File(localUri);
-                    final Uri uriForFile = FileProvider.getUriForFile(context, BuildConfig.APPLICATION_ID + FILE_PROVIDER_EXTENSION, file);
-
-                    final Intent openFileIntent = IntentUtils.createOpenFileIntent(uriForFile, mimeType);
-                    showSnackbarForFilename(openFileIntent, context, fileName);
+                    final String fileName = URLUtil.guessFileName(Uri.decode(localUri), null, mimeType);
+
+                    final File file = new File(Uri.decode(localUri));
+                    if (file.exists()) {
```
Comment (pocmo) [inline app/src/main/java/org/mozilla/focus/broadcastreceiver/DownloadBroadcastReceiver.java]: I'd either remove this check - now that we expect this file to always exist.

Or: Throw an exception (like IllegalStateException) so that we see a crash and know that there are still issues.
