### PR TITLE
Fix crash while double tapping a tab inside tablist (#1385)

### LINKED ISSUE #1385: Crash while double tapping a tab inside tablist.
Firefox focus always crash when I double tap any tab inside tablist.

### PR DESCRIPTION
**Pull request by codebu5ter**
Fixes #1385

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/session/ui/SessionsSheetFragment.java [hunk 1]
```diff
@@ -102,10 +102,12 @@ public void onAnimationEnd(Animator animation) {
         animator.addListener(new AnimatorListenerAdapter() {
             @Override
             public void onAnimationEnd(Animator animation) {
-                getActivity().getSupportFragmentManager()
-                        .beginTransaction()
-                        .remove(SessionsSheetFragment.this)
-                        .commit();
+                if (getActivity() != null) {
+                    getActivity().getSupportFragmentManager()
```
Comment (pocmo) [inline app/src/main/java/org/mozilla/focus/session/ui/SessionsSheetFragment.java]: Even if the first call returns a non null activity, the second call can still return null.

Comment (codebu5ter) [reply app/src/main/java/org/mozilla/focus/session/ui/SessionsSheetFragment.java]: @pocmo The first call returns a non null activity, and hence the code under the 'if' statement is executed, but the second call returns a null, and hence nothing is done, preventing the crash.
This seems to be working fine as per my testing.

Comment (pocmo) [reply app/src/main/java/org/mozilla/focus/session/ui/SessionsSheetFragment.java]: If the second call returns null then this would be a NullPointerException again.

Don't you want to do something like this:

```java
final Activity activity = getActivity();
if (activity != null) {
    activity.getSupportFragmentManager() ....
    ...
}
```

File: app/src/main/java/org/mozilla/focus/session/ui/SessionsSheetFragment.java [hunk 2]
```diff
@@ -98,14 +99,17 @@ public void onAnimationEnd(Animator animation) {
 
     /* package */ Animator animateAndDismiss() {
         final Animator animator = playAnimation(true);
+        final MainActivity activity = (MainActivity)getActivity();
```
Comment (sputnikci) [inline app/src/main/java/org/mozilla/focus/session/ui/SessionsSheetFragment.java]: \[Checkstyle\] ERROR: 'typecast' is not followed by whitespace\.

Comment (sputnikci) [inline app/src/main/java/org/mozilla/focus/session/ui/SessionsSheetFragment.java]: \[Checkstyle\] ERROR: 'typecast' is not followed by whitespace\.

Comment (pocmo) [reply app/src/main/java/org/mozilla/focus/session/ui/SessionsSheetFragment.java]: I wonder why you are doing this here and not in onAnimationEnd()? With this we are keeping a reference to the activity the whole time unnecessarily.

Also the cast to MainActivity does not seem like something we need to do.

Comment (codebu5ter) [reply app/src/main/java/org/mozilla/focus/session/ui/SessionsSheetFragment.java]: @pocmo Shifted the activity reference to inside onAnimationEnd().
Also, without the typecasting, getSupportFragmentManager() is unable to get resolved, because it requires a reference to an AppCompatAcitivty. I can either typecast to an AppCompatAcitivty or MainActivity. I've chosen the latter since it extends AppCompatAcitivty.

**Comment by pocmo** [comment]
Looks good now! Can you squash those two commits into a single one? Then it's ready to merge. :)

**Comment by codebu5ter** [comment]
@pocmo Done! :)

**Comment by codebu5ter** [comment]
@pocmo  I’m not sure, but this may also solve #1375
